apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-modelcar
spec:
  workspaces:
    - name: output
  params:
    - name: WORK_DIRECTORY
      description: Directory to use
      type: string
    - name: VERSION
      description: Version of the application
      type: string
  steps:
    - name: build
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/appuio/oc:v4.19
      script: |
        #!/bin/sh
        oc new-build . --name=sample-chat-model -l app=sample-chat-model -l app.kubernetes.io/name=sample-chat-model --strategy=docker || rc=$?
        oc start-build sample-chat-model --from-dir=. --follow --wait
        oc tag sample-chat-model:latest sample-chat-model:$(params.VERSION)