apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: mlops-inference-stack
spec:
  selector:
    matchLabels:
      project: mlops-inference-stack
  template:
    metadata:
      labels:
        fleet: mlops-inference-stack
    spec:
      os:
        image: quay.io/flightctl-demos/mlops-inference-stack
      applications:
        - name: inference-stack
          appType: quadlet
          image: image-registry.openshift-image-registry.svc:5000/inference-stack-quadlet:b1e5e8ca8e
      config:
        - name: inference-server-metrics
          gitRef:
            repository: flightctl-demos
            targetRevision: main
            path: demos/mlops-inference-stack-demo/configuration
