apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  name: mlops-inference-stack
spec:
  selector:
    matchLabels:
      project: mlops-inference-stack
  template:
    metadata:
      labels:
        fleet: mlops-inference-stack
    spec:
      os:
        image: quay.io/flightctl-demos/mlops-inference-stack
      applications:
        - name: inference-stack
          appType: quadlet
          image: image-registry.openshift-image-registry.svc:5000/inference-stack-quadlet:1f2d868749
      config:
        - name: inference-server-metrics
          gitRef:
            repository: mlops-inference-stack
            # TODO reset to main
            targetRevision: mlops-inference-server-demo
            path: /demos/mlops-inference-stack-demo/configuration
